name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # ✅ Make sure npm installs optional dependencies (needed for rollup native binary)
  NPM_CONFIG_OPTIONAL: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Clean everything and recreate lockfile on Linux so it includes rollup's native optional package
      - name: Clean install state
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Recreate lockfile with optional deps
        run: npm install --package-lock-only --no-audit --no-fund --include=optional

      - name: Install deps (honor optional)
        run: npm ci --no-audit --no-fund --include=optional

      # ✅ Call Vite via Node to avoid .bin permission quirks
      - name: Build
        run: node node_modules/vite/bin/vite.js build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
